# Generated by Django 3.0.9 on 2020-09-18 12:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20190812_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('body', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 9, 18, 15, 7, 18, 733340))),
                ('comes_from', models.CharField(choices=[('System', 'System'), ('Employer', 'Employer')], default='System', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee')),
            ],
        ),
    ]
