# Generated by Django 3.0.9 on 2020-09-18 16:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import employee_dashboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190812_1652'),
        ('employee_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 19, 40, 31, 398471)),
        ),
        migrations.CreateModel(
            name='Employee_Extra_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, height_field=100, null=True, upload_to=employee_dashboard.utils.media_uploader('profile_imgs'), width_field=100)),
                ('work_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remotely', 'Remotely')], default='Full Time', max_length=20)),
                ('work_location', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('hiring_date', models.DateField()),
                ('end_of_contract', models.DateField()),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], default='Single', max_length=10)),
                ('base_salary', models.FloatField()),
                ('direct_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_manager', to='core.Employee')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Employee')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to='core.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=employee_dashboard.utils.media_uploader('contracts'))),
                ('employee_extra_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_dashboard.Employee_Extra_Info')),
            ],
        ),
    ]
