# Generated by Django 3.0.9 on 2020-09-18 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import employee_dashboard.utils


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0002_auto_20200918_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_extra_info',
            name='base_salary',
            field=models.FloatField(validators=[employee_dashboard.utils.positive_validator]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 21, 22, 29, 839439)),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GOSI_salary', models.FloatField(validators=[employee_dashboard.utils.positive_validator])),
                ('deductions', models.FloatField(validators=[employee_dashboard.utils.positive_validator])),
                ('deductions_reason', models.TextField(blank=True, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days_absent', models.PositiveIntegerField(default=0)),
                ('employee_extra_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee_dashboard.Employee_Extra_Info')),
            ],
        ),
    ]
