# Generated by Django 3.0.9 on 2020-09-19 13:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
import employee_dashboard.utils


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0003_auto_20200918_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', models.TimeField()),
                ('to', models.TimeField()),
                ('days_of_week', models.CharField(max_length=7, validators=[employee_dashboard.utils.days_of_week_string_validator])),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 16, 6, 5, 690089)),
        ),
        migrations.CreateModel(
            name='Shift_Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_extra_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_dashboard.Employee_Extra_Info')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_dashboard.Shift')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent'), ('On Leave', 'On Leave')], max_length=20, null=True)),
                ('employee_extra_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_dashboard.Employee_Extra_Info')),
            ],
        ),
    ]
