# Generated by Django 3.0.9 on 2020-09-19 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0004_auto_20200919_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 17, 30, 36, 201812)),
        ),
    ]
