# Generated by Django 3.0.9 on 2020-09-19 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0005_auto_20200919_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=datetime.date(2020, 9, 19)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 18, 31, 47, 669104)),
        ),
    ]
