# Generated by Django 3.0.9 on 2020-09-19 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0006_auto_20200919_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 18, 33, 50, 638493)),
        ),
    ]
