# Generated by Django 3.0.9 on 2020-09-21 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0012_auto_20200920_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 19, 2, 25, 226440)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_dashboard.Employee_Extra_Info'),
        ),
    ]
