# Generated by Django 3.0.9 on 2020-09-21 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0013_auto_20200921_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 19, 3, 54, 387066)),
        ),
    ]
