# Generated by Django 3.0.9 on 2020-11-17 16:47

import datetime
from django.db import migrations, models
import employee_dashboard.utils


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0014_auto_20200921_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.CharField(default='0', max_length=150, validators=[employee_dashboard.utils.validate_latitude]),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.CharField(default='0', max_length=150, validators=[employee_dashboard.utils.validate_longitude]),
        ),
        migrations.AddField(
            model_name='employee_extra_info',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='employee_extra_info',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Prof', 'Prof'), ('Master', 'Master'), ('Miss', 'Madam'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Mr', 'Mr'), ('Ms', 'Ms'), ('Eng', 'Eng'), ('Dev', 'Dev')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee_extra_info',
            name='status',
            field=models.CharField(choices=[('Active', 'Actice'), ('Left', 'Left')], default='Actice', max_length=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='mode',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash'), ('Check', 'Check')], default='Bank', max_length=10),
        ),
        migrations.AddField(
            model_name='shift',
            name='polygon',
            field=models.TextField(default=1, validators=[employee_dashboard.utils.validate_polygon]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 19, 47, 5, 873397)),
        ),
    ]
