# Generated by Django 3.0.9 on 2020-11-17 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import employee_dashboard.utils


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0015_auto_20201117_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 19, 52, 50, 460854)),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(default=datetime.date(2020, 11, 17))),
                ('file', models.FileField(upload_to=employee_dashboard.utils.media_uploader('reports'))),
                ('employee_extra_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee_dashboard.Employee_Extra_Info')),
            ],
        ),
    ]
