# Generated by Django 3.0.9 on 2020-11-29 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0018_auto_20201117_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 4, 47, 13, 677255)),
        ),
    ]
