# Generated by Django 3.0.9 on 2020-11-29 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_dashboard', '0019_auto_20201129_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 4, 48, 6, 244104)),
        ),
    ]
